data:
  root: "/vast/as16513/data"
  ImagenetA: 
    path: "ImagenetA"
    params:

  ImagenetC: 
    path: "ImagenetC"
    params:
      - "all"
      - "all"
      - 
          - 1
          - 2
          - 3
          - 4
          - 5
  
  ImagenetR:
    path: "ImagenetR"
    params:

  ImagenetV2:
    path: "ImagenetV2"
    params:
      - "all"

  Imagenet1KTest:
    path: "ILSVRC2012/test"
    params:

  Imagenet1KVal:
    path: "ILSVRC2012/val"
    params: