data:
  root: "/vast/km5939/data"
  ImagenetA: 
    path: "ImagenetA"
    params:

  ImagenetC: 
    path: "ImagenetC"
    params:
      - "all"
      - "all"
      - 
          - 1
          - 2
          - 3
          - 4
          - 5
  
  ImagenetR:
    path: "ImagenetR"
    params:

  ImagenetV2:
    path: "ImagenetV2"
    params:
      - "all"

  Imagenet1KTest:
    path: ""
    params:

  Imagenet1KVal:
    path: ""
    params:
